Add: Seção "O que é o DASI?"
DiretorTI-DASIUSP/SiteDasi pull request #39
Opened 2024-06-06 20:00 UTC by ka3ych

## Criação da seção DASI

- Adicionei imagem do brasão do Dasi em `public/images`
- Adicionei fonte **Rubik** no arquivo `index.js`

Tentei seguir o padrão do proposto na task, mas acabei fugindo um pouco por conta das `props` do componente `SecaoDasi`, daí criei o componente `App` para importar a SecaoDasi passando as props. 

- Tive que separar o título em 2 partes, dividindo-o em torno de "DASI", para conseguir estilizar o "DASI"

(Coloquei o parágrafo que estava em [site](https://dasiusp.com/home) para ver como ficava)

Perdão pelas gambiarras 😁

2024-06-18 01:17 UTC, Miguel03706 commented on src/components/SecaoDasi.jsx
> +                    {partesTitulo[0]}
uma recomendação: ao invés de você usar tipo "partesTitulo[0]", voce poderia fazer tipo "partesTitulo.img"

2024-06-18 01:24 UTC, Miguel03706 reviewed
Da uma olhadinha nos comentários que eu deixe, é bem simples de arrumar, acho q vai ser bem de boas pra arrumar, o código em si eu amei, ta muito bem feito, não vejo muitas coisas pra mudar, só a recomendaçãozinha q eu coloquei no codigo mesmo

2024-06-18 03:31 UTC, ka3ych commented
## Mudanças
Reestruturei a estrutura de `Props` para usar um JSON na parte do Título da página.
(Não sei bem se é assim que faz, mas tentei! Consegui entender um pouco sobre esse assunto, mas pesquisarei mais sobre!!)

Tem problema eu deixar o componente `App` ou preciso exportar diretamente o componente `SecaoDasi`, para seguir exatamente como está a task?

2024-07-15 19:28 UTC, F1NH4WK commented on src/components/SecaoDasi.jsx
> +const Props = {
Logo, você pode só copiar cada valor aqui e substituir lá em cima nas linhas 16, 17, 18  e 23.

2024-07-15 19:31 UTC, F1NH4WK requested changes
Dito isto, você só precisa arrumar o código pra ele ficar dinâmico. Eu até poderia fazer um commit arrumando, mas vou deixar esta tarefa pra você!

2024-08-01 21:22 UTC, ka3ych commented on src/components/SecaoDasi.jsx
Olá, tudo bom?

Arrumei o componente deixando-o estático, coloquei o título, descrição e imagem diretamente nas tags.
Perdão a demora, estive ocupada ultimamente :)

2024-08-05 15:11 UTC, Miguel03706 approved these changes
por mim está perfeito, e fica em paz katarina, estava com sdds do seus PR, admito, mas a gente acaba ficando ocupado mesmo ao decorrer da graduação, torço muito pra que você continue dando uma força pra gente e agradeço muito pelo seu trabalho viu. Ficou muito bom, de verdade

2024-08-06 16:40 UTC, F1NH4WK approved these changes

2024-08-06 17:02 UTC, merged