Adcionei o Footer
DiretorTI-DASIUSP/SiteDasi pull request #40
Opened 2024-06-28 22:30 UTC by jvpascale

Todos os comentários estão no código, aprendi html css recentemente então qualquer comentário é bem vindo.
No começo achei meio confuso porque é um pouco diferente do html/css tradicional, mas dps q entendi a estrutura deu para fazer.

2024-07-03 17:01 UTC, Miguel03706 commented on public/images/instagram-logo-thin.svg
Os icones ficaram meio "pequenos", o traço deles, principalmente quando a tela der uma aumentada, vão perdendo a qualidade, eu recomendo pegar um icone do instagram no site do [flaticon](https://www.flaticon.com/br/icone-gratis/logotipo-do-instagram_87390?k=1720025859269&log-in=google), ja deixei linkado uma imagem ai do insta, ai você vai em "editar icone" e deixa a cor dele branca, baixa em png, acredito que o maior tamanho seja melhor(512x512), mas ai você pode baixar em tamanhos diversos e ir testando pra ver qual se encaixa melhor mesmo

2024-07-03 17:01 UTC, Miguel03706 commented on public/images/instagram-logo-thin.svg
o mesmo vale para a imagem do linkedin

2024-07-03 17:13 UTC, Miguel03706 commented on src/components/Footer.jsx
> +    font-family: Arial;
Em relação as fontes utilizadas, eu recomendaria você dar uma olhada no figma
![image](https://github.com/DiretorTI-DASIUSP/SiteDasi/assets/75583778/d6f487d7-0e45-4421-a9db-be76b877824d)
se você dar uma olhada, ali tem a fonte utilizada, o tamanho dela e tudo mais, caso você não saiba onde baixar essas fontes e tals tem o site do [Google fonts](https://fonts.google.com/), basicamente a gente sempre pega as fontes de la se tratando de sites, tem esse [video](https://www.youtube.com/watch?v=7--Bn9KLRI4) aqui para te ajudar, recomendo que use o @import, ele é mais de boas, e normalmente o mais usado também.

2024-07-03 17:22 UTC, Miguel03706 commented on src/components/Footer.jsx
> +const TextosFooter = styled.div`
O footer ta MUITO legal, mas ele só tem um pequeno probleminha, que admito que antes eram separadas em duas missões, mas agora elas meio que se tornaram uma só, então fica em paz em relação a isso, mas ai a gente ja arruma por aqui mesmo kkkk, que é o seguinte, o footer por enquanto só está sendo bem utilizado no celular, no computador ele acaba não ficando **responsivo**, ai pra isso, eu tenho esse [video](https://www.youtube.com/watch?v=fKk_GFjNfJc) pra te recomendar, que ele mostra como a gente faz pra usar as **medias-queryes** e isso é MUITO importante para o desenvolvimento de sites responsivos, e também, algo que te ajuda MUITO no desenvolvimento de sites num geral é o [Inspencionar elementos](https://www.youtube.com/watch?v=Ht4jVYemFLA), tem esse video explicando um geral, mas assim, você pra essa atividade, só vai precisar do que ele fala aos 3min +-, que é a questão da responsividade, então tipo, você vai usar as medias queryes pra definir um tamanho e vai ir testando, com telas menores, maiores e tals, ate que fique bom, dá pra dar uma boa brincada nesse sentido, até você se familiarizar com a ferramenta e com as "medias queryes"

2024-07-03 17:27 UTC, Miguel03706 requested changes
Eu deixei alguns comentários no código, depois a gente tem mais alguns pequenos pontos para aprimorar, mas por enquanto, eu vou te deixar com esses pontos de melhoria, mas que ja fique constado que eu AMEI o footer, gostei muito de você estar participando, fiquei genuinamente feliz :) e assim, ta muito legal, agora é so a gente ir lapidando ele aos poucos, ai você ja ganha uns conhecimentos bem massa na questão de responsividade também, vai ser bem legal, e assim, parabens, de vdd, mesmo que precisem de mudanças, está um código muito bom, funcional també,. organizadinho, qualquer dúvida, pode entrar em contato comigo, ou com o eduardo também, a gente está cuidando dessas partes de feedback de código e tudo mais. Bom trabalho amigo, e saiba que você está indo pelo caminho certo. Parabéns😼👊

2024-07-15 19:14 UTC, F1NH4WK approved these changes

2024-07-19 23:24 UTC, F1NH4WK approved these changes
### Eae, Taboão, suave?
Primeiramente, quero te parabenizar por ter contribuido com o site do DASI. Como seu amigo, sei que não foi fácil ter de aprender **do zero** HTML, CSS e React tendo que lidar com as coisas da vida e os conteúdos da própria faculdade. Veio no meu privado tirar dúvidas, trabalhou até na Campus Party! Mandou muito cara, que determinação. Agora, vamos ao código.

### Comentários Gerais
Sua estrutura HTML do Footer ficou **perfeita**, não tive de alterar nada, você pegou bem a ideia de box. Além disso, você desenvolveu **mobile-first** e deixou **documentado** cada linha do código, muito foda! As únicas alterações ocorreram em um problema comum, no CSS, que possui muitas maneiras de fazer a mesma coisa. Sua dificuldade foi a mesma da @ka3ych, utilizar medidas absolutas **(px)**.  Evite ao máximo utilizar ela, pois os **pixels** são medidas que são funcionais apenas pra tela onde você está programando e em alguns casos mais complexos.

### Minhas alterações

Se você checar os commits d0bfe33e376842c9b319b215159c45f4606040db e be6db20ef044e2e9a9060fbc2d7cebeeb0a2da6b, vai ver que a maior parte das alterações foram substituindo **px por em/rem**. Você pode conhecer mais sobre essas medidas, que são bem simples, [clicando aqui](https://dev.to/lazarocontato/quando-utilizar-rem-em-ou-pixel-cf0). Ademais, outra dica é **evitar ao máximo utilizar a propriedade height**. Sei que parece meio maluco, mas o height é uma das propriedades mais quebradas do CSS, usando ela você vai ter dor de cabeça pra deixar o site responsivo, vai por mim. O que usar, então? No lugar do height, você pode utilizar o padding, funciona bem melhor, no seu código você vai perceber que eu troquei o **height do Footer por um padding**, onde uso a medida *em*.

### Observações finais

Usar o `position: relative` no elemento pai e `position: absolute` foi uma ótima sacada, mas não era necessário utilizar essa propriedade no Mobile, apenas no Desktop. Inclusive, você vai notar que:
```css
width: calc(100% - 10em); // 100% - padding-horizontal do elemento pai
```

É um belo macete pra centralizar elementos absolutos, fica a dica. Por fim, analise minhas alterações, é uma ótima forma de aprender, qualquer dúvida  é só me chamar! Obrigado pela contribuição.

2024-07-20 16:41 UTC, Miguel03706 approved these changes

2024-07-20 17:15 UTC, F1NH4WK commented
Pode dar merge aí Miguel, não consigo acessar a conta do DASI :(

2024-07-31 19:02 UTC, merged