Add barra de navegação
DiretorTI-DASIUSP/SiteDasi pull request #43
Opened 2024-08-26 23:32 UTC by ka3ych

- como não consegui fazer para a nav um translate da direita para a esquerda (o que acredito ser mais bonito, mas estava com alguns probleminhas), fiz o contrário
- adicionei também uma animação nos links quando o usuário passar o mouse por cima

- parece meio estranho o menu na resolução de um tablet, por exemplo, qualquer coisa eu modifico isso
![oiu](https://github.com/user-attachments/assets/c8cfed7d-c169-42e0-8471-04829ee565e9)

2024-08-27 00:07 UTC, Miguel03706 requested changes
Eu AMEIIIIIIIIIIIIIIIIIIII, karina, tu é mto clean véii, ficou INCRIVEL, eu amei os efeitos, vc deixou os codigos bonitinhos, seguindo uma hierarquia bonitinho, facil de ler e entender, boa logica, lançou a braba no css tbm. Ai eu requisitei umas mudanças, mas vou dar um feedback mais acertivo no telegram :) mas ficou lindo perfeito e maravilhoso viu s2

2024-08-27 00:07 UTC, Miguel03706 commented on src/components/Navigation.jsx
> +            left: -50vw;
por fim, mudar esse "left: -50vw" para: "right: -50vw;"

2024-08-27 00:07 UTC, Miguel03706 commented on src/components/style.css
esse arquivo aqui, adimito que eu não entendi bem o motivo dele existir kkkkk, nos meus testes eu apaguei ele, e não reparei em nenhuma diferença, ai assim, se ele n estiver sendo usado, o ideal era excluir, e se ele estiver sendo usado, se for possivel, passar para dentro do jsx, ao inves de ficar no css;

2024-08-27 02:40 UTC, ka3ych commented on src/components/style.css
Esse arquivo eu tinha esquecido de excluir, perdão

2024-08-27 02:48 UTC, ka3ych reviewed
- - - - - - Deu certo aqui! Agora a barra de navegação abre na direita

1. Arrumei umas medidas da versão desktop

1. Como não consegui fazer a navegação interna da página só passando o id do elemento no href, botei um pouco de js para isso. E como não temos todas as partes ainda da página, é melhor colocar todos os links depois (Só seguir o padrão do `onClick={(e) => clickLink(e, 'id do elemento')`) e adicioná-lo nos `a` do menu.

2024-08-27 22:57 UTC, Miguel03706 approved these changes

2024-08-28 02:14 UTC, F1NH4WK approved these changes

2024-08-28 12:55 UTC, merged